name: Feature Request
description: Suggest a new feature or improvement for claude-code-automation
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please describe what you would like and why it would be useful.

  - type: textarea
    id: description
    attributes:
      label: Description of the feature
      description: A clear and concise description of the feature you would like.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case / motivation
      description: Why do you need this feature? What problem does it solve?
      placeholder: |
        I want to automate ... because ...
        Currently I have to manually ...
    validations:
      required: true

  - type: dropdown
    id: automation-type
    attributes:
      label: Proposed automation type
      description: Which automation type do you think this feature relates to?
      options:
        - Hook
        - Skill
        - Subagent
        - Permissions
        - CLAUDE.md
        - Custom Command
        - MCP Server
        - LSP Server
        - Agent Team
        - New type
        - Not sure
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context, examples, or screenshots that help explain the feature.
      placeholder: Add any additional context here...
    validations:
      required: false
